host = "tcp:clublacrosse.database.windows.net,1433"
username = "sql_admin@clublacrosse"
passwd = "DCdc4646"
database = "clubstats"
table = "[data].[tourneymachine_mainpage_data]"
driver = "{ODBC Driver 13 for SQL Server}"